# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-06 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TextField(),
        ),
    ]
