# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-03 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(max_length=50),
        ),
    ]
